### ISSUE TITLE
Say hi to anh Loc

### ISSUE THREAD

**Issue by hoangdat** [xuanloct4/daw-purchases#1]
Hi anh Loc,
I am very like the way you work with `ReSwift`. Did you work with that before?

**Comment by hoangdat** [comment]
I have some comments
```
1. How do you handle Router if we have ScenceDelegate supported? And further, multi ScenceDelegate ?
2. You are using force cast for some properties in model class, for example: in Purchase class, we have productId is force cast. What happen if data from remote changed from int type to string type? Can we have a property here with optional type and have a default value when mapping ?
3. Can we have immutable data inside State class? For example, in SearchState class, all properties are declared as var. Can we make it immutable by using let ?
4. There is a library supports for executing async action (api call, …) https://github.com/ReSwift/ReSwift-Thunk
```

**Comment by xuanloct4** [comment]
Thanks Dat for your comment.

I did not work with ReSwift before.
In this project, I learn about ReSwift and ReSwiftRouter and then decided to use them to achieve the goal of the exercise for unidirectional MVVM

**Comment by xuanloct4** [comment]
About your comment,
Sorry for the late reply.
1. I did not try RxSwiftRouter for SceneDelegate before, But in case if we have SceneDelegate supported, It turns out to be pretty much the same as the way we implemented it in AppDelegate.
Follow this guide for how to programmatically set up your app with Scene Delegate.
And move the code inside the function` application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool`
to the function ` scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions)`
It is very simple

2. It is not a force casting because we use it for property declaration, it is called unspecified-property.
Agree with you that for Serializing data from API, we should use Optional ("?")
But currently, we do not care much about the value of these properties, thus I mark them as "!" for handy usage.
I will update it later if have time.
3. Of course, we can not have immutable data inside the `State` class because its value will change frequently.
Agree with you that I can miss declaring some property as `var`, so if I have time I will update them as `let` later.  
4. There are a lot of ways to execute async actions, I did not use `ReSwift-Thunk` so I will study it. But I think Rxswift is a good selection for this project.
You could see that all API requests are also executed async, I have just used Rxswift for zipping and merging the Result from Requests to build the final Product Info.
I wrote a very convenient 'NetworkService' class for executing Request, the Result from Request can be handle in callback or can be emitted from `Observables` of `RxSwift`

**Comment by xuanloct4** [comment]
Thanks again for your comments, 
If have any other questions, feel free to ask me, I will reply when I have time
